### ISSUE TITLE
Update OTLP RDS secret creation with random name

### ISSUE THREAD

**Issue by weslleycamilo** [nearform/otlp-blueprint#132]
Related to: https://github.com/nearform/otlp-blueprint/issues/124

As this is a dev environment with constant tests destroying and recreating it seems to be better use a random name for the rds secret manager otherwise we are going to face issues like below:
![image](https://user-images.githubusercontent.com/19431474/201162829-d1f6b50d-82f6-4d59-bc22-98916d2a465e.png)

![image](https://user-images.githubusercontent.com/19431474/201162857-8ef17db7-2ea9-4575-ac82-36ea6c099625.png)

**Comment by jdarling** [comment]
This was done as part of #184
