### ISSUE TITLE
Add kubernetes support

### ISSUE THREAD

**Issue by zimny** [nearform/otlp-blueprint#272]
The task is to create a variation open telemetry deployment and deploy it to kubernetes.

- The deployment should use the open telemetry collector k8s operator to deploy collector.
- There should be all scripting (makefile? look at https://github.com/nearform/k8s-kurated-addons/ for ideas) needed to deploy kind cluster.
- Front-end application should be deployed on a simple ngnix server that will be deployed on the same cluster.
- Back-end deployed as a simple kubernetes workload (pod/deployment/service?) or knative application.
- Images must be available in a public registry. 

- There should be an option to deploy collector as a single instance or a two-layered approach that will enable tail based sampling (traces). 
- Collector should send traces into jeager as a backend.
- All relevant properties should be exposed as environment variables.

**Comment by simoneb** [comment]
Who's working on this one?

**Comment by heidermassu** [comment]
> 

@andreacfm and I was working on this one. Now @nearform-kenan going to review my PR
