### ISSUE TITLE
Colima/Lima/Rancher support

### ISSUE THREAD

**Issue by zimny** [nearform/otlp-blueprint#83]
It seems there's some issue with running docker-compose with other tool than docker e.g. colima or rancher. 

The task is to find out it that can be fixed or there's some limitation in the tooling.

```
frontend                    | glob error [Error: EACCES: permission denied, scandir '/root/.npm/_logs'] {
frontend                    |   errno: -13,
frontend                    |   code: 'EACCES',
frontend                    |   syscall: 'scandir',
frontend                    |   path: '/root/.npm/_logs'
frontend                    | }
```

**Comment by jdarling** [comment]
Rancher deprecated compose support in 2.x so I don't think we should worry about it anymore.

Worth adding kompose.io support to the list though to ensure that the project can easily be stood up on K8s.

**Comment by jdarling** [comment]
With the latest versions of the codebase, Docker, and Colima this seems to be working just fine.  Will continue testing with other orchestrators.

**Comment by jdarling** [comment]
All base orchestrators seem to work out of the box with the latest versions.  Closing this ticket.
